import Image from "next/image";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <main>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate, pariatur impedit maiores explicabo sapiente labore delectus iure doloremque nostrum repellat nisi aspernatur sit quas corrupti, consequatur, alias amet enim? Possimus quis modi aut nulla reprehenderit fugit error deserunt magni provident, ad voluptatem quia nesciunt ratione ipsum numquam voluptatum repellat distinctio dolores quaerat minima! Nihil sapiente ipsa recusandae fugit incidunt voluptatibus voluptas debitis nam unde harum nemo placeat tenetur odit facere quas aliquid quibusdam quam, obcaecati officia! Consequuntur numquam rem tempora nam ipsa eius quia quas repellendus voluptas corporis debitis, fugit quidem quasi vel cum, deserunt nihil. Minus psum dolor, labore incidunt. Consequatur, esse ab nisi earum odio rerum illo cum saepe reprehenderit magnam maiores nam eaque voluptatibus, autem nesciunt, culpa dolorem ea possimus nihil optio iusto explicabo? Ad tempore ut voluptas tempora perspiciatis explicabo molestias recusandae! Nostrum possimus perspiciatis suscipit libero inventore sunt alias corrupti accusamus at quos temporibus, atque provident unde ut laboriosam repellendus delectus voluptas. Vero, soluta sed, perspiciatis voluptates ad quam officiis ipsum quidem, dolorem nesciunt at qui rem? Cupiditate corporis dicta fuga commodi nihil dolores tempore quaerat laudantium cum quis? Culpa quibusdam sed est. Unde aliquam exercitationem earum officia illo. Autem vero maxime excepturi nemo dolorem dolores illum tempora sunt a porro. Excepturi sint itaque perferendis iure numquam, doloribus dolor dolorem saepe asperiores. Corrupti saepe sequi totam optio inventore. Quia, similique vitae? Perspiciatis mollitia excepturi maiores similique recusandae unde quia. Magni impedit ducimus, esse architecto corrupti placeat sed quia libero dolor cum! Atque maxime doloremque adipisci quibusdam temporibus id distinctio sed et quae nemo! Quisquam reiciendis perferendis fugit magni corporis eius consectetur aliquid at, beatae omnis velit tenetur obcaecati! Quisquam, officia expedita magnam, consequatur eius fugiat recusandae odio optio, quos cum sunt. Aliquid doloremque provident tempora eveniet natus! Dolores alias vero id, porro fugiat laudantium placeat minus adipisci in, a consequuntur sit ipsa. Corporis non recusandae ipsa est harum ab nesciunt. Assumenda voluptatem nam expedita nemo vel eaque voluptatibus accusantium suscipit. Aperiam, molestias! Reprehenderit cupiditate veritatis, ex hic inventore iure, et eum fugit quos, explicabo repellat amet dolorem recusandae.</p>
    </main>
  );
}
